### PR TITLE
JSX/XML

### PR DESCRIPTION
**Pull request by simonsmith**
Tweaks XML/JSX to match HTML as much as possible.

screen shot 2016-05-18 at 14 00 01

Also added a note about using polyglot as a lot of these changes depend on those syntax files.

### CODE REVIEW

**Comment by joshdick** [comment]
When you say "these changes", are you referring to your other PRs, this one, or both? I did a random (but admittedly not very thorough) sampling of some of the highlight groups in your other PRs and many of them seem to be stock Vim ones.

**Comment by simonsmith** [comment]
After testing it it does seem as though the JSX/XML one is the only syntax so far with a hard dependency on a plugin. The other syntax files do work, but the stock Vim ones don't look quite as good as some of the addons in polyglot. Think it might be worth recommending polyglot/syntax plugin usage or just leave it out?

**Comment by joshdick** [comment]
> The other syntax files do work, but the stock Vim ones don't look quite as good as some of the addons in polyglot.

Not sure what you mean by "other syntax files here"? As in, the other PRs don't include polyglot-specific highlight groups, but the polyglot-provided syntax files use the generic highlight groups more effectively?

I would like the color scheme to remain "dependency-free" and thus not rely on plugins for language-specific syntax highlighting, although I'll admit that it's a slippery slope with the "Plugin Highlighting" section (which styles things provided by plugins, but isn't language-specific.)

**Comment by simonsmith** [comment]
Sorry for not being clear. By 'other' I do mean stock. It's worth noting that the JS section caters for two JS syntax plugins as well as the default.

I'm not sure that JSX support would be possible without a plugin though?

**Comment by simonsmith** [comment]
My thoughts were that whilst additional syntax plugins are not a requirement, by adding the popular ones (as found in polyglot for example) then onedark can enhanced for those users.

**Comment by joshdick** [comment]
I looked at this again -- it seems that the highlight groups in this PR [are built into stock Vim](http://ftp.vim.org/vim/runtime/syntax/xml.vim) after all?

I'm okay with leaving the polyglot comment in README.md, but can you tack ", but is not required" on the end of it? :)

**Comment by simonsmith** [comment]
The XML works yeah, but the JSX plugin adds a `javascript.jsx` filetype which allows highlighting in JS files. 

I noticed you added a polyglot link already so I'm happy to remove that README line if you like.

**Comment by simonsmith** [comment]
Rebased with just the syntax colour changes

**Comment by joshdick** [comment]
👍 I added an additional note about vim-polyglot to the README anyway. :)

**Comment by simonsmith** [comment]
Nice one 👍

**Pull request merged**
