### PR TITLE
Tweak CSS syntax highlighting

### PR DESCRIPTION
**Pull request by simonsmith**
Just minor improvements

**Atom**

screen shot 2016-05-09 at 09 53 50

**Vim**
screen shot 2016-05-09 at 10 24 12

### CODE REVIEW

**Comment by joshdick** [comment]
If we're going to tweak CSS support, might as well add other comment highlight groups (`cssTagName`, `cssPseudoClassId`, `cssIncludeKeyword`, `cssColor`, etc.)

**Comment by simonsmith** [comment]
I see yes. Do you know where the central list for these things exists?

**Comment by joshdick** [comment]
`:syntax list` might be your best bet, though the output is quite overwhelming :)

**Comment by joshdick** [comment]
This may also be useful: http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

**Comment by simonsmith** [comment]
Oh nice, `:syntax list` is perfect. I'll revise these PRs

**Comment by joshdick** [comment]
Awesome, thanks very much!

**Comment by simonsmith** [comment]
Updated, and added SCSS too.

**CSS (Atom)**
screen shot 2016-05-10 at 11 31 14

**CSS (Vim)**
screen shot 2016-05-10 at 11 31 59

**SCSS (Atom)**
screen shot 2016-05-10 at 11 31 18

**SCSS (Vim)**
screen shot 2016-05-10 at 11 31 35

**Comment by joshdick** [comment]
👍

**Pull request merged**
