### PR TITLE
Better selection color

### PR DESCRIPTION
**Pull request by webdesus**
Better selection color for omnifunc and WildMenu(#62)

### CODE REVIEW

**Comment by simonsmith** [comment]
Hey @webdesus, mind adding a screenshot too? Just aids the review.

**Comment by webdesus** [comment]
**omnifunc**
vim_omnifunc
**WildMenu**
vim_wildmenu

**Comment by joshdick** [comment]
Thanks for the PR!

**Comment by simonsmith** [comment]
Yes, the dropdown highlighting has been great so far. A good addition

**Pull request merged**
