### PR TITLE
Perl syntax highlighting

### PR DESCRIPTION
**Pull request by MegOBonus**
Add syntax highlighting for Perl

### CODE REVIEW

**Comment by simonsmith** [comment]
Hey @MegOBonus,

Thanks for this. Could you add a screenshot for review?

**Comment by MegOBonus** [comment]
Hi @simonsmith 
perlhighlight

**Comment by simonsmith** [comment]
Thanks, how does it compare to Atom?

**Comment by MegOBonus** [comment]
This color scheme a little bit different than original color scheme of Atom. But to my mind, this looks better.

**Comment by MegOBonus** [comment]
After change

perl

**Comment by simonsmith** [comment]
I've had a look in Atom and your changes at some Perl files and I agree with `perlVarPlain` being blue instead of red. The Atom theme (and this theme on master) have way too much red 👍 

However two changes I'd make:

```diff
-call s:h("perlStatementInclude", { "fg": s:red })
+call s:h("perlStatementInclude", { "fg": s:purple })
-call s:h("perlFunction", { "fg": s:red })
+call s:h("perlFunction", { "fg": s:purple })
```
screen shot 2017-02-27 at 10 52 37

Having purple for those keywords looks a little less harsh and inline with some of the other syntax styles and Atom itself.

**Comment by simonsmith** [comment]
Do you think we should set `call s:h("perlPOD", { "fg": s:comment_grey })` as well? I'm not familiar with Perl but it looks like the following should be greyed out?

screen shot 2017-02-27 at 10 58 25

Like this:
screen shot 2017-02-27 at 10 58 36

**Comment by MegOBonus** [comment]
You are right. It's comment and it must be gray.

**Comment by simonsmith** [comment]
Also, could you make your changes to the template file? More details are [in the CONTIRBUTING.md](https://github.com/joshdick/onedark.vim/blob/master/CONTRIBUTING.md).

**Comment by MegOBonus** [comment]
Sure.

**Pull request closed without merging**
