### PR TITLE
Added Ruby Language Syntax Markup

### PR DESCRIPTION
**Pull request by zelint**

### CODE REVIEW

**Comment by joshdick** [comment]
Thanks for your PR. Some questions:

1. Why did you uncomment all of the commented colors if they remain unused?
2. Why are all of the "need to check color" comments there?

**Comment by zelint** [comment]
First PR.  Just learning.  Please advise.

**Comment by joshdick** [comment]
No worries! Two more questions:

1) I'm  curious why you added `s:default_bg`?
2) I saw that you removed the "need to check color" comments, but what was the meaning behind them? I see that thy were all previously on highlight groups that were set to be red; were those comments there since you weren't sure how those highlight groups are used? I ask because I don't code in Ruby so I'm not sure what your intention was (will there be too much red?)

**Comment by zelint** [comment]
1. I didn't look to see if the black color was used anywhere.  I felt the true background color was a bit lighter at least in the terminal.  Maybe black isn't used anywhere else and it won't matter.
2. Yes I was unsure about the highlight group.  However, I knew that they options are available so I included them, but maybe this doesn't make sense and I should leave them off?

**Comment by zelint** [comment]
I gave it a bit more love.  Please review.

Thanks.

**Comment by joshdick** [comment]
1) I just noticed that you are setting `t_Co`; that line should be removed since the theme works in both 256- and 16-color modes.

2) `s:black` is used for the `Normal` and `Cursor` highlight groups; I'm still not clear on why you changed the cterm value? Are you saying it's closer to the color from the original One Dark Atom theme?

Everything else looks good to me!

**Comment by zelint** [comment]
1.  I am using the default terminal in Ubuntu, the syntax highlight fails to work unless t_Co gets set.  I am not sure how to get around this.

2. Yes in the cterm the lighter color matched the theme a bit closer (in my opinion).  But I maybe wrong?

**Comment by joshdick** [comment]
1. You should set `t_Co` in your `~/.vimrc`, but the theme should not include it. That setting refers to the number of colors supported by the terminal, which will be different for different users' machines, which is why that setting should be omitted from the theme.

2. You changed the cterm black value from 235 to 234, which is actually a *darker* color, not lighter. I'd leave the original as-is.

**Comment by joshdick** [comment]
👍

**Pull request merged**
