### PR TITLE
[WIP] Allow users to override color definitions in their .vimrc

### PR DESCRIPTION
**Pull request by FredDeschenes**
This allows you to override a color across the board, without
having to call "onedark#set_highlight" for each affected highlight.

Just add:
```vim
let g:onedark_color_overrides = {
\ "black": {"gui": "#2F343F", "cterm": "235", "cterm16": "0" },
\ "purple": { "gui": "#C678DF", "cterm": "170", "cterm16": "5" }
\}
```
in your .vimrc **before** `colorscheme onedark`.

I haven't looked into getting this to work with the lightline/airline themes yet (thus the "WIP" in the title), I wanted your opinion on the feature before getting myself into this, but if you're interested in the feature I can probably make it work with those too.

### CODE REVIEW

**Comment by FredDeschenes** [comment]
For the record this had no conflicts before you merged your tweaks branch :P

I'll merge the changes when I have some time later today, this is mostly about getting your opinion on the feature anyway.

**Comment by joshdick** [comment]
I felt bad seeing your PR come in right as I was about to merge my own!  😆 

I like this idea since it's useful and simple, but without getting the lightline/airline themes working, it might be slightly confusing to use.

The lightline/airline themes used to reference Vim highlight groups directly before the templating system went in, but changes to the main `onedark.vim` kept accidentally breaking those themes, which is why I switched them to use templating/to reference colors directly.

**Comment by FredDeschenes** [comment]
No worries, I saw you'd made the other branch this morning and nearly started my work from there but decided against it for... whatever reason.

As I mentioned, I only wanted to check the interest in getting something like this merged, seeing as you like the idea I'll go ahead and check how it can be applied to the lightline/airline themes and update the PR accordingly.

**Comment by FredDeschenes** [comment]
So, this works for airline and lightline (I'm guessing we don't really need to worry about the .xresources for this), but it's not exactly pretty. I was thinking about adding a function in autoload/onedark.vim to return the dictionary with all the correct colors to use and just call this from the other places, what do you guys think about that?

**Comment by joshdick** [comment]
First of all, thanks for pursuing this!

If we were to keep going this direction, the manual installation instructions in the README (and the text you added about the overriding not working for the lightline/airline themes) would have to be updated.

That said, I have conflicting thoughts about your solution to add `autoload/onedark.vim`, at least in its current state:

* It makes `onedark.vim` and the airline/lightline themes no longer distributable as single, standalone files, which is probably fine, but in that case:
* It somewhat undoes the need for the templating system, since `autoload/onedark.vim` itself could basically serve as the "color reference" file; a big reason I added the templating system in the first place was to prevent the need for the generated files to depend on each other. I'm not sure what that would mean for the terminal color palette files, though.

Thoughts?

**Comment by joshdick** [comment]
(Another option would to just permanently keep the lightline/airline themes non-overridable, essentially keeping what you had as of c8df982.)

**Comment by FredDeschenes** [comment]
Yeah I realized I could remove the whole templating thing for all the files (except .Xresources) as I pushed this and felt pretty much the same way as you do.

8f40230 is only to remove duplicated code, we could still have the color overriding stuff for airline/lightline (with 79178c2) without having the extra autoload file. Just have to be a little more careful if adding new colors, but it's still just copy/paste in the end and I don't think this happens too often anyway.

(Btw I'll update the docs and rebase this once everything's set)

**Comment by joshdick** [comment]
I took some time to think about this.

I think the Xresources file needing to coexist with any other file (in `autoload` or otherwise) justifies keeping the templating system, and if it's going to stay, it probably still make sense to use the templating system for all theme files directly (the 79178c2 approach), instead of using the `autoload` approach.

That said, I am not sure whether omitting colors that are not used in the lightline/airline themes from their corresponding templates would be beneficial or not, since keeping them in (as they appear in  79178c2) would probably make it easier to copy and paste template changes from the main theme.

**Comment by joshdick** [comment]
(Had started writing a reply here but deleted it pretty quickly after, need to think a little more! ;P)

**Comment by joshdick** [comment]
I took some time to think about this and waffled back and forth on it all weekend. :)

I think the Xresources file needing to coexist with any other file (in `autoload` or otherwise) justifies keeping the templating system. Even so, I think taking the `autoload` approach makes sense, even while keeping the templating system, since it gives us:

* Less duplicated color definition code, and less code overall
* No need for unused color definitions in the airline/lightline themes
* No need for the Vim/airline/lightline themes to be generated from templates

So, given that direction, here's what I think is left:

* Update README.md and CONTRIBUTING.md as necessary
* Remove onedark.vim/airline/lightline templates since colors no longer need to be substituted into them

Finally, I also had a crazy idea that we could use `autoload/onedark.vim` as the canonical color definition file so that even **that file** would no longer need to be a template, and that we could somehow parse **that file** to extract colors in order to generate the .Xresources file, but that might be an idea for another PR. :)

**Comment by FredDeschenes** [comment]
Sounds good, I'll go ahead and remove the extra templates and update the doc accordingly!

**Comment by FredDeschenes** [comment]
That should do it (unless I forgot something in the doc)!

**Comment by joshdick** [comment]
Made some minor tweaks on top of this, and have squash-merged all of the changes in separately.

I didn't realize I had left the README.md comment for the airline/lightline themes around "must be used in conjunction with onedark.vim" while that wasn't true for a time, even though it's true once again; good catch!

Thanks for your patience and contribution! 🎊

**Comment by FredDeschenes** [comment]
You're welcome, I'm just glad I don't have to keep a fork just to set my background color!

**Comment by simonsmith** [comment]
Nice work! 🎉

**Pull request closed without merging**
